### ISSUE TITLE
initial issues

### ISSUE THREAD

**Issue by colinallen** [inpho/inphosemantics-frontend#1]
Glad to see this moving forward.  A few alpha issues...

In the selection panel, the four different Beagle models are there in triplicate.

Unsure how long to wait...  so could use some sort of wait indicator. However, have tried several hits from different browsers and with one exception nothing shows up under headers.  Hitting reload removes even the headers.

A couple of times, the x button in the panel to remove a model didn't work, but I can't replicate that at the moment.

**Comment by rrose1** [comment]
Could you open up the first and third points as separate issues? And then we can edit so as to focus it in the second point.

Could you try the following? Select 'SEP: Complete' and add it. Select 'Beagle: Composite' and add it. Finally type in 'metaphysics' and hit enter. Then Submit. It should open up a result right away.

If that works, try an additional search phrase for the same corpus and model choice and submit again. It should take about 10 seconds.

Finally, try 'SEP: Complete' and 'Beagle: Order' and a single search term. Most likely those vectors haven't been loaded. Give it 1-2 minutes.

Let's see which of these it fails.

**Comment by rrose1** [comment]
Could you also make 'progress indicator' a separate issue?

**Comment by colinallen** [comment]
For me it's failing at the 'right away' bit after taking first two steps then submitting 'metaphysics'.  (Tested with Firefox, Safari, and Camino).

**Comment by rrose1** [comment]
Have you hit enter after typing in 'metaphysics'? I.e., such that it's on a line below with an 'X' after it?

**Comment by colinallen** [comment]
ah - that was it!  operator error, like I said...  since it persisted in the box between loads I assumed it was there.

**Comment by rrose1** [comment]
No doubt the operator should get feedback as to whether he/she has submitted a complete set of parameters. Would you mind making this an issue as well?
