### ISSUE TITLE
model/corpus not removed by x

### ISSUE THREAD

**Issue by srwaggon** [inpho/inphosemantics-frontend#13]
In the selection modal, if a [model/corpus/phrase] is selected, and the page is refreshed, the selected items will persist in the selection modal. However, they will lose the ability to be removed. Only newly-entered items will be removable.

This has to do with the similarities and contrasts between the ways that the hash-data propagates onto the page. The newly-entered data enters with an on-click function which is closed over the list item to be removed. The persisting elements lack this onclick attachment, and thus need to receive similar treatment.

Although this would be simple enough to fix, considering that this happens more than twice (6, in fact), it may be wise to abstract out the idea into a function and simply make the call six times rather than have 6x replicated code.

**Comment by rrose1** [comment]
Is the idea that the currently selected items (with their callbacks) in the menu should be rendered (generated) using the data in the hash? So in fact hitting add corpus, for example, would a) update the hash b) force a redraw of the menu based on the updated hash?

**Comment by srwaggon** [comment]
This is indeed the idea. To fix this I have done the following: I have copied the callbacks used in the 'add model/corpus/phrase' button handlers to the page-persistence handling.

Not the cleanest solution, as stated above, but working for now. Cleanliness solutions can be considered part of bug report #12.
