### ISSUE TITLE
corpus/model, term not available graphics

### ISSUE THREAD

**Issue by rrose1** [inpho/inphosemantics-frontend#14]
Let's assume that the front end is like a partial function. It's not defined on all inputs. But it also doesn't know in advance which inputs these are until it tries to evaluate. (a) The user might enter a term not in a lexicon; or (b) a model that a corpus hasn't been trained on.

Assume that the front end can consult an oracle and get a clear signal as to whether (a) or (b) happens. (See issues #2 and #4). What will the user see in the relevant column? A shaded column with a message?

Of course, this front end functionality can be made available before #2 and #4 are available.

**Comment by colinallen** [comment]
I like the idea of the shaded column+message (e.g. "this data/corpus combination is not currently available")

**Comment by rrose1** [comment]
The server now delivers informative error messages such as 'Corpus not available', 'Model not available' and 'Phrase not available'. Furthermore, the column-rendering post request has been extended to include an error callback function, which currently just prints a message to the console log.

To test this using tinytornado-simulated.py (say you want to simulate the 'Corpus not available') modify the IndexHandler class so that instead of

self.write(result)

in the definition of 'post' it has 

self.send_error()

and add this definition to the IndexHandler class:

def write_error(self, status_code, **kwargs):
    self.finish('Corpus not available')

**Comment by srwaggon** [comment]
This is closed I believe?
