### ISSUE TITLE
misaligned columns

### ISSUE THREAD

**Issue by rrose1** [inpho/inphosemantics-frontend#15]
The table entries fall out of alignment if the headings wrap. Try entering SEP Phil Mind and SEP Complete. The first wraps and so pushes down its entries.

**Comment by wpettyjohn** [comment]
I'm not seeing it. Maybe it's an issue with screen size?

**Comment by rrose1** [comment]
Have you tried adding three corpora? You're right that it has to do with available width. In any case, the text does wrap; and if it wraps more in one column than in another, as it may if the labels are of different length, the entries no longer line up.

**Comment by wpettyjohn** [comment]
I tried it with three corpora and at a view different browser zooms (or whatever one would call that), and even when the corpora headings wrap, it doesn't misalign anything. I'm also using tinytornado-simulated.py with my most recent layout updates, so maybe that's why I'm not seeing it?

**Comment by rrose1** [comment]
Have you noticed that when you resize the browser window to a small enough width, the labels wrap?

**Comment by srwaggon** [comment]
With items atomized into divs with a fixed height, and a pattern for controlling overflow, this no longer is a problem either.
