### ISSUE TITLE
Rendered Table Data is Bland: Discontinuity Absent?

### ISSUE THREAD

**Issue by srwaggon** [inpho/inphosemantics-frontend#17]
After the requests have been sent out and return, we render the table data into several very tall columns. As they all sit side-by-side, this becomes somewhat overbearing to look at. I believe that it would be much more pleasing to view given that there were some visual separator between phrases, possibly also between models and between corpora.

A given solution might to provide wells to each phrase column so that they seem atomic unto themselves. Another suggestion given was to have an alternating style, whereas every other column might have a darkened background.

This possibly goes as well for models and corpora.

**Comment by colinallen** [comment]
Good idea.  The well idea sounds initially more interesting to me, but will need to take a look to be sure.

**Comment by srwaggon** [comment]
Columns are atomized into divs now.
