### ISSUE TITLE
highlight same term across columns

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/inphosemantics-frontend#19]
One thing that is painful on the current interface is seeing when the same term appears in multiple lists - so perhaps implementing something that makes the same term bold in all lists if you mouseover it would help this discontinuity. Another option would be changing the background class to highlight the term.

**Comment by colinallen** [comment]
Right -- my suggestion was just to color code the repeated terms across the lists.  Either the words could be colored, or their backgrounds.  (Latter will probably be easier to use, I think.)

**Comment by srwaggon** [comment]
As it stands, this issue is closed. Like terms across columns highlight on mouse-over.

**Comment by colinallen** [comment]
Great! -- just note issue logged under panels regarding highlighting parts of the list that are outside scroll zone.

**Comment by srwaggon** [comment]
I'm not exactly sure what you mean. Try rephrasing what you said?

**Comment by colinallen** [comment]
This was a reference to https://github.com/inpho/inphosemantics-frontend/issues/20#issuecomment-6477540
