### ISSUE TITLE
Export Modal needs better Exception Handling

### ISSUE THREAD

**Issue by srwaggon** [inpho/inphosemantics-frontend#26]
The data export modal needs more support for handling exceptions in the event that an export query is malformed (just a possibility) or possibly incomplete. An example of an incomplete query would be a query which is missing a parameter, whereas a malformed query could contain a phrase which is not available.

**Comment by colinallen** [comment]
This ticket has been open for 5 months.  Remove the option from the menu until it can be dealt with.

**Comment by srwaggon** [comment]
Option removed as of today and pushed to master branch.
