### ISSUE TITLE
feature request: progress indicator

### ISSUE THREAD

**Issue by colinallen** [inpho/inphosemantics-frontend#3]
Would be nice to have a 'loading' indicator while similarities are being computed

**Comment by srwaggon** [comment]
There is now a spinning dial indicating server-side work.

A progress bar would be better but I'm not sure if we're able to predetermine how long it will take the server to calculate similarities.

**Comment by JaimieMurdock** [comment]
The progress bar necessitates having a push-notification system or some 
sort of job queue interface. Might be nice long-term, so we can cancel 
inactive requests, but it's definitely a non-trivial problem.
