### ISSUE TITLE
uncaught error

### ISSUE THREAD

**Issue by colinallen** [inpho/inphosemantics-frontend#31]
http://inphodata.cogs.indiana.edu:8080/?corpora=sep.complete&models=beagle.composite&phrases=conclusion%2Cpremise%2Ctherefore&searchLimit=20 

yielded 'uncaught' error in the box for 'therefore'

**Comment by srwaggon** [comment]
Belayed for now.

Seemed to be caused by an empty list (empty term-similarity table) returned from <ModelViewerInstance>.get_similarities(<term>, True) which was then queried for its (absent) data.

Further uncaught errors may crop up but this instance has been resolved.

Pushed to master branch.
