### ISSUE TITLE
everything in triplicate

### ISSUE THREAD

**Issue by colinallen** [inpho/inphosemantics-frontend#4]
In the selection panel, the four different Beagle models are there in triplicate.

**Comment by srwaggon** [comment]
This is a result of being able to run each model on each corpus. This is intended in the future to come with stipulations, enhancements, or caveats. As an example, we may later want to disable a specific corpus-model association.

A good solution to this would be to display only the available models for each corpus (which, is currently all), but by requiring that the user select a corpus prior to model.

Given that all combinations of corpus/model/phrase are queried and run based on the selections, it is true that it is indeed redundant to show all possible models for all possible corpora as available considering that each corpus can be trained through each model.

**Comment by srwaggon** [comment]
Resolved. Switched population mechanism to reading from an object (dictionary) rather than an array containing duplicates. This can be quickly reversed in the event that we need to use specific combinations (e.g.: sep.complete-beagle.context or iep.complete-beagle.order).
